alekmaul/pvsneslib

tools/gfx2snes/Makefile
tools/gfx2snes/gfx2snes.c

Hello!
I've made some improvements in gfx2snes tool to support more BMP image formats, including BI_RLE8 compression.
Hope you find them useful.

Added BMP BI_RLE8 compression support.

---

.gitignore
compiler/tcc-65816/Makefile
compiler/tcc-65816/configure
tools/bin2txt/Makefile
tools/constify/Makefile
tools/gfx2snes/Makefile
tools/smconv/Makefile
tools/snesbrr/brr/Makefile
tools/snestools/Makefile

- some fixes to build the whole project
- updated tcc confguration to prepare an ARM compatible version

minor bug fixes

---

compiler/tcc-65816/Makefile
tools/gfx2snes/Makefile
tools/snestools/Makefile

Few makefiles update to build it on ARM

ARM compatibility

---

devkitsnes/bin/816-opt.py

Hi,
Here a simple PR to reformat `816-opt.py` script.
* Convert for loop into list comprehension
* Simplify boolean if expression
* Reformat code with black (python tool)

816 opt.py formating and python3 best pratices

---

pvsneslib/include/snes/map.h
pvsneslib/include/snes/object.h

Spyke -> Spike

---

.gitignore

Realign develop with commit did on master

Chore: Update .gitignore

---

snes-examples/debug/debug.c

fix: FPS->COUNTER

---

tools/816-opt/Makefile

Hi all,
Here I just refactored the `Makefile` for 816-opt to reflects same changes from `bin2txt` and `constify`. It's almost variable renaming.

816-opt: Refactor Makefile

---

tools/snestools/Makefile
tools/snestools/snestools.c

Hi Antho,
Same player shoot again. This PR is a continuation of the others makefile_xxxx.

Makefile snestools

---

tools/tmx2snes/Makefile
tools/tmx2snes/tmx2snes.c

Hi all,
Here the last optimisazion for the makefiles in `tools/`
I also change the print version, in the same way than the others tools.

Optimize tmx2sne makefile

---

.github/workflows/pvsneslib_build_package.yml
Makefile
devkitsnes/snes_rules

Hi all,
A small PR to answer to last talks with @RetroAntho.

New features

---

devkitsnes/snes_rules
tools/816-opt/src/helpers.h

Hi all,
Here a quick and dirty fix to solve the Alek's issue with .db (truncated).
I will **maybe** change it later to use malloc/realloc to make it more dynamic and to cover all the case, even the long long long lines.

Fix Alek's issue

---

.github/workflows/pvsneslib_build_package.yml
compiler/Makefile
docker/centos/Dockerfile
docker/debian/Dockerfile
docker/fedora/Dockerfile
docker/ubuntu/Dockerfile
tools/816-opt/Makefile
tools/816-opt/src/helpers.c
tools/816-opt/src/helpers.h

Hi all,
Here the fix to compile on Windows, linux and Macos without the need to install extra tools or lib.
Tested via the runners, locally. Docker should work as well, I'm testing it in the evening and fix it if needed.
Regards

Fix to compilation issues on Windows, linux and Macos (dyn vs stat libs)

---

.gitmodules
compiler/Makefile

Hi all,
Here the PR to update tcc.

Update tcc version, update the Makefile for compilers

---

.github/workflows/pvsneslib_build_package.yml

Hi,
I remove unnecessary directory creation during checkout (github action, build runner).

Remove useless directory

---

tools/816-opt/src/helpers.h

Here the quick and dirty fix to solve the #239 issue.
Please let the issue open I would like to fix it in a better way. 
An alternative could be to switch from snprintf to sprintf, but it can lead to a buffer overflow.

Fix the issue #239

---

.github/workflows/pvsneslib_build_package.yml
tools/816-opt/src/helpers.c
tools/816-opt/src/optimizer.c

This PR should fix the issue #241.
@RetroAntho Can you try it from your side ?

Fix buffer overflow who could lead to undefined behavior

---

devkitsnes/snes_rules

Hi,
This change add the feature mentioned in the issue #203.
To use it, just set SRC before to include the snes_rules in your Makefile.

Add feature: issue #203

---

pvsneslib/source/backgrounds.asm

Fix a comment in bgSetScroll for REG_BGyHOFS.

fix: fix comment in bgSetScroll for REG_BGyHOFS

---

snes-examples/logo/snes-logo-capcom/src/logo.c

Color math fadeout for Capcom Logo.

feat: color math fadeout for Capcom Logo
