tools/bin2txt/bin2txt.c

Trying to build everything on Linux, this will help if we could remove the `strupr` usage (or use this implementation)
`strupr` is non-standard functions from Microsoft's C library.
Haven't try my changes on Windows, if you can do it??

Add strupr implementation for non non-MS toolchain builds

---

snes-examples/graphics/Sprites/DynamicSprite/DynamicSprite.c

1) Bug Description
When A is pressed in DynamicSprite sample, the sprite is not updated.
2) Solution
For an unknown reason `padkeya` value is not equal to 0 even if it is set in the while loop:
```
if(pad0 & KEY_A) {
// if not yet pressed
if (padkeya == 0) {
padkeya=1;  // avoid adding new sprite continuisly
// add new sprite to queue
addSprite((&gfxpsrite)+8*4*2, ADRGFXSPR);
}
}
else
padkeya=0;
```
Initializing `padkeya` to 0 before the while loop solves this issue.

DynamicSprite sample bugfix: For an unknown reason padkeya value is not equal to 0.

---

tools/bin2txt/Makefile
tools/bin2txt/bin2txt.c

Fix bin2txt compilation problem with MINGW

Better handling of missing strupr for bin2txt under linux

---

tools/smconv/it2spc.h

This error is caused by the program originating from Visual Studio, which
sometimes supports things standard compliant compilers don't support.
This merge request closes #79.

Correct extra qualification on member error

---

devkitsnes/snes_rules
pvsneslib/source/crt0_snes.asm
pvsneslib/source/videos.asm
readme.md

- Update to the last version of wla which now contains the -d flag to disable WLA's ability to calculate A-B where A and B are labels. Will fix bugs with the "breakout" sample
- Added more details in the description of the home page
- moved m7* variables to a specific ramsection to avoid see it everywhere (point discussed with Alekmaul). The 2 examples of mode 7 still works like before, no impact seen !

wla update

---

tools/gfx2snes/gfx2snes.c

it's easy to miss when a more mild error occurs in gfx2snes so I think it would be good if they were colored red

feat: colored errors for gfx2snes more noticeable

---

pvsneslib/Makefile

Hi all,
In the same way, a small optimization for the `Makefile` used by `pvsneslib/`.
The changes are:
The export statements can be moved inside the variable definition, and we don't need to export TOPDIR since it's not used outside this Makefile.
The @echo command in the docs target can be made into a single line to avoid unnecessary output.
The if statement in the docs target can be simplified by using @[ -f warn.log ] && cat warn.log to output the `warn.log` file.
This version uses "$(MAKE)" instead of "make" to ensure that the make command is correctly overridden if the user specifies a different make command. 
It also uses "@rm" instead of "rm" and "@mkdir" instead of "mkdir" to suppress command echoing, and removes unnecessary semicolons at the end of some commands.
The mkdir …

Optimize Makefile for pvsneslib

---

tools/Makefile

Hi all,
Here a small update for the `tools/Makefile` to optimize it.
This optimized `Makefile` simplifies the code and reduces duplication by using the automatic variable `$(MAKECMDGOALS)` to pass the command goal (all, clean, or install) to the sub-Make processes. Here's a breakdown of the changes:
The phony targets are listed together with the `SUBDIRS` variable, which makes the `Makefile` more readable and easier to maintain.
The all, clean, and install targets all depend on the subdirectories, so they can be listed together with the PHONY target, and then listed as prerequisites for each of the targets.
The rule to build each subdirectory is simplified using the $(MAKE) command and the automatic variable $@, which represents the current subdirectory. The `$(MAKECMDGOALS)` variable is …

Optimize and simplify Makefile for tools/

---

tools/snesbrr/base/basemath.h

Hi all,
Here a very small change to avoid warnings messages during the `snesbrr` compilation:
```
basemath.h: In instantiation of ‘T base::math::clamp(T) [with unsigned int N = 16; T = int]’:
BrrCodec.cpp:202:30:   required from here
../base/basemath.h:68:26: warning: left operand of shift expression ‘(-1 << 15)’ is negative [-fpermissive]
68 |                 low = -1 << (N - 1)
|                       ~~~^~~~~~~~~~
../base/basemath.h: In instantiation of ‘T base::math::clamp(T) [with unsigned int N = 15; T = int]’:
BrrCodec.cpp:244:26:   required from here
../base/basemath.h:68:26: warning: left operand of shift expression ‘(-1 << 14)’ is negative [-fpermissive]
../base/basemath.h: In instantiation of ‘T base::math::clamp(T) [with unsigned int N = 4; T = int]’:
BrrCodec.cpp:441:34: …
```

Remove warnings message during snesbrr compilation

---

compiler/Makefile

Hi all,
Here some small improvements for the `compiler/Makefile`.
- The `Makefile` now defines variables for directory paths and build types to improve readability and maintainability.
- The default number of jobs to run in parallel is now based on the available CPU cores, which should improve build times.
- The default target has been set using the `.DEFAULT_GOAL` directive, so it's not necessary to specify the target on the command line.
- The phony targets have been declared explicitly using the `.PHONY` directive, which is considered good practice.
- The configure step for `tcc` is now a separate target that can be invoked independently, which may help with debugging or development.
- The `Makefile` now uses `$(MAKE)` instead of hardcoded `make` to improve portability.
- The …

Optimize Makefile to build tcc and wla-dx

---

tools/constify/Makefile
tools/constify/constify.cpp

Hi all,
Some small improvements for `constify`. I slighty optimized the `Makefile` and remove useless new lines in `constify.c` when printing version.
In this optimized version, I made the following improvements:
- Consolidated common flags into `CFLAGS` and `DEFINES` variables
- Uses `:=` instead of `=` for variable assignment to prevent unnecessary re-evaluation.
- Uses `$(shell date +%Y%m%d)` instead of invoking the date command multiple times.
- Moved the platform-specific `LIBS` flag into an `ifeq` block for better readability
- Simplified the object file generation rule to use a pattern rule instead of repeating the recipe for each object file
- Added quotes around `$@` and `$<` in recipe commands to handle filenames with spaces (maybe useful for Windows target)
- Added dependencies …

constify: Remove extra new line when version is printed, optimize Makefile as well

---

Makefile

Hi all,
Just a small update for the Makefile at the root of the repository.
Tested.

Optimize Makefile

---

Makefile

Hi all,
Just a tiny fix for `Doxygen`. It's only mandatory to build a release.

Fix doxygen prerequesite, we only need it to build release

---

.github/workflows/pvsneslib_build_package.yml
tools/816-opt/Makefile
tools/816-opt/src/helpers.h

- add libpcre2 to the MSYS2 build workflow
- change 816-opt Makefile to use libpcre2 instead of libtre for regex on Windows
- change 816-opt/src/helpers.h to use PCRE2 header instead of regex.h (same API) on Windows
See also https://github.com/daniel-starke/pvsneslib/actions/runs/5684683944.
Reference: https://github.com/alekmaul/pvsneslib/issues/224

Fix issue #224

---

snes-examples/logo/snes-logo-pvsneslib/src/logo.c

Improvement for "Made with PVSnesLib" logo screen:
- Use `framesCounter` instead of `logoTimer` that has same role

improve: use framesCounter instead of logoTimer that has same role

---

snes-examples/games/likemario/map_1_1.tmj
snes-examples/maps/mapscroll/tiledMario.tmj
snes-examples/maps/tiled/Makefile
snes-examples/maps/tiled/maplevel01.tmj
snes-examples/objects/mapandobjects/tiledMario.tmj
snes-examples/objects/nogravityobject/mapzelda.tmj
tools/tmx2snes/Makefile
tools/tmx2snes/tmx2snes.c

This change fixes the problem of tmx2snes when it tries to check if the version of the tmj file (tiled) is supported.
This error is due to the fact that we are trying to compare versions using floats.
Here the error:
`
convert map tiled ... map_1_1.m16
/home/kobenairb/workspace/tests/pvsneslib-last/devkitsnes/tools/tmx2snes map_1_1.tmj tiles.map
tmx2snes: Loading map: [map_1_1.tmj]
tmx2snes: error 'the export version you used (1.9) is not yet supported. The tool supports only the versions from 1.9 to 1.1.'
`
This change includes the patch in tmx2snes and the update of tmj files (tiled). I used the latest version of Tiled to do this. I also updated the tmx2snes version to 1.0.1.
I think this change requires a review, I'm not convinced of the relevance of my method to transform a float into …

Tiled: Fix tmx2snes version check and update tmj files

---

pvsneslib/source/maps.asm

affect to mapGetMetaTilesProp and mapGetMetaTile

Fix: mask out tile number on flipped tiles

---

snes-examples/logo/snes-logo-capcom/Makefile
snes-examples/logo/snes-logo-konami/Makefile
snes-examples/logo/snes-logo-pvsneslib/Makefile

Rename the logo roms name so they can correctly be copied in `snes-examples/bin` folder.

improve: rename logo roms name

---

tools/smconv/it2spc.cpp

soundbank.asm now fill banks with HiROM mapping, following -i usage. This is necessary or sound will be broken.

SMCONV fix

---

pvsneslib/source/videos.asm

-remove unnecessary "dea", the paletteSize parameter act now as the number of colors you want to get
-add rep $#20 before inc, that solves the page boundery issue, when an array in wram overlaps two pages

Fix bug getPalette
